---
title: "Baseline characteristics"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Descriptive statistics for two CRC case-control datasets.

```{r, results = "asis", echo = F, message = F, warning = F}
# Load functions
prepcrc1 <- function(){

  library(tidyverse)
  library(haven)
  crc <- read_sas("clrt_caco_metabo.sas7bdat")
  
  # Metadata and WCRF scores (keep on local drive because big file)
  wcrf <- read_dta("Wcrf_Score.dta") %>% select(Idepic, Wcrf_C_Cal)
  
  # Remove duplicated Idepics (with dplyr or base)
  meta <- read_dta("clrt_caco.dta") %>% select(-Match_Caseset, -Country, -Center, -Cncr_Caco_Clrt) %>%
    distinct(Idepic, .keep_all = T)
  
  # meta.dedup <- meta[!duplicated(meta["Idepic"]), ]
  
  # Converted to dta
  # write_dta(data, "clrt_caco_metabo.dta")
  
  # Subset biocrates concentrations
  # concs <- crc %>% select(Acylcarn_C0 : Sugars_H1, -Batch_MetBio)
  concs <- crc %>% select(matches("Acylcarn_|Aminoacid_|Biogenic_|Glyceroph_|Sphingo_|Sugars_"), 
                           -starts_with("Outdq"))
  
  # Subset biocrates data by taking !is.na > 0
  biocrates <- apply(concs, 1, function(x) sum(!is.na(x)) > 0)
  
  # Subset Biocrates subjects only
  crc1 <- crc[biocrates, ]
  crc1 <- crc1 %>% inner_join(meta, by = "Idepic")
  
  var.list <- c("Country", "Center", "Sex", "Match_Caseset", "Smoke_Stat", "L_School")
  crc1 <- crc1 %>% mutate_at(vars(var.list), as.factor)
  
  #class(crc1$Sex)

}
prepcrc2 <- function(){
  library(haven)
  wcrf <- read_dta("Wcrf_Score.dta") %>% select(ends_with("_Cal"), Idepic)
  crc2 <- read_csv("biocrates_p150.csv")
  crc2 <- crc2 %>% left_join(wcrf, by = "Idepic")
  
  var.list <- c("Country", "Center", "Sex", "Match_Caseset", "Smoke_Stat", "L_School")
  crc2 <- crc2 %>% mutate_at(vars(var.list), as.factor)
}

# Run code
crc1 <- prepcrc1()
crc2 <- prepcrc2()

crc1a <- crc1 %>% 
  select(Sex, Age_Blood, Height_C, Weight_C, Bmi_C, Qe_Energy, Country, Pa_Mets, Smoke_Stat, 
         Wcrf_C_Cal, Cncr_Caco_Clrt) %>% mutate(Study = "CRC1")
crc2a <- crc2 %>% 
  select(Sex, Age_Blood, Height_C, Weight_C, Bmi_C, Qe_Energy, Country, Pa_Mets, Smoke_Stat, 
         Wcrf_C_Cal, Cncr_Caco_Clrt) %>% mutate(Study = "CRC2")
crcmetab <- bind_rows(crc1a, crc2a)

library(qwraps2)
options(qwraps2_markup = "markdown")
crc1_summaries <-
  list("Total subjects"   =
         list("N"   =   ~ n()),
       "Sex" = 
         list("Female"   =  ~ n_perc0(Sex == 1),
              "Male"     =  ~ n_perc0(Sex == 2)),
       "Age at blood collection" = 
         list("Mean"     =  ~ mean_sd(Age_Blood)),
       "Height" =
         list("Mean (SD)" = ~ mean_sd(Height_C)),
       "Weight" =
         list("Mean (SD)" = ~ mean_sd(Weight_C)),
       "BMI" =
         list("Mean (SD)" = ~ mean_sd(Bmi_C)),
       "Total energy intake" =
         list("Mean (SD)" = ~ mean_sd(Qe_Energy, na_rm = T, show_n = "never")),
       "Country" = 
         list("France"      =  ~ n_perc0(Country == 1),
              "Italy"       =  ~ n_perc0(Country == 2),
              "Spain"       =  ~ n_perc0(Country == 3),
              "United Kingdom"       =  ~ n_perc0(Country == 4),
              "Netherlands" =  ~ n_perc0(Country == 5),
              "Greece"          =  ~ n_perc0(Country == 6),
              "Germany"      =  ~ n_perc0(Country == 7),
              "Denmark"      = ~ n_perc0(Country == 9)),
       "Physical activity" =
         list("Mean (SD)" = ~ mean_sd(Pa_Mets, na_rm = T, show_n = "never")),
       "Smoking status" =
         list("Non smoker" =  ~ n_perc0(Smoke_Stat == 1),
              "Never smoker"   =  ~ n_perc0(Smoke_Stat == 2),
              "Smoker"       =  ~ n_perc0(Smoke_Stat == 3)),
              #"Unknown"      =  ~ n_perc0(Smoke_Stat == 4)),
       "WCRF score" = 
         list("Mean (SD)" = ~ mean_sd(Wcrf_C_Cal, na_rm = T, show_n = "never"))
  )
st1 <- summary_table(group_by(crc1a, Cncr_Caco_Clrt), crc1_summaries)
st2 <- summary_table(group_by(crc2a, Cncr_Caco_Clrt), crc1_summaries)
both <- cbind(st1, st2)
print(both, cnames = c("CRC1 cases", "CRC1 controls", "CRC2 cases", "CRC2 controls"))
```

