# Figures for manuscript table 2

library(ggplot2)
library(tidyverse)

# Load coefficients as generated by CRC_get_signatures.R
load("coefficient_tables.Rdata")
sig1 <- pltdata %>% filter(abs(Coefficient) > 0.019)
sig2 <- faplot %>% filter(abs(Coefficient) > 0.02)
sigall <- bind_rows("Fatty acid signature" = sig2, "Endogenous metabolite signature" = sig1, 
                    .id = "Signature")

# Signature plot with arrows (facetted)
ggplot(sigall, aes(y = 0, yend = Coefficient, x = reorder(compound, -abs(Coefficient)), 
                   xend = reorder(compound, Coefficient), colour = Signature)) + 
geom_hline(yintercept = 0, linetype = "dotted") +
geom_segment(arrow = arrow(length = unit(0.06, "inches"), type = "closed"), arrow.fill = NULL) + 
scale_colour_manual(values = c("blue", "red")) +
geom_vline(xintercept = 0, linetype = "dashed") +
ylab("Coefficient on first PLSR latent variable") + theme_classic() +
theme(axis.title.x = element_blank()) +
#facet_grid(. ~ fct_inorder(Signature), scales = "free") +
facet_wrap(. ~ fct_inorder(Signature), scales = "free") +
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, colour = "black"),
      axis.ticks.y = element_line(), strip.background = element_blank(),
      #axis.ticks.x = element_blank(), 
      strip.text.x = element_text(size = 11),
      panel.spacing = unit(2, "lines"),
      legend.position = "none") #+ ggtitle("B")


nlist <- c("Maintain normal\nbody weight", "Be moderately\nphysically active", 
           "Limit foods that\npromote weight gain", "Eat mostly\nplant foods", "Limit red and\nprocessed meat", "Avoid\nalcohol", 
           "Overall WCRF/\nAICR score")

# Correlation plot with CIs (method 1) (probably the best)
#source("WCRF_components_sig.R")
#pcor.ci <- readRDS("df_wcrf_correlations.rds")
ggplot(pcor.ci, aes(x=fct_inorder(component) %>% fct_relabel(~nlist), 
        y=estimate, colour = fct_inorder(Model), shape = fct_inorder(Model))) + 
geom_errorbar(width=0.2, aes(ymin = conf.low, ymax = conf.high), 
                position= position_dodge(width = 0.7), colour = "grey40") +
geom_point(size = 3, position = position_dodge(width = 0.7), stroke = 1) +
scale_colour_manual(values = c("red","blue","blue")) +
scale_shape_manual(values = c(18,18,20)) +
geom_hline(yintercept = 0, linetype = "dashed", colour = "grey") +
xlab("WCRF/AICR recommendation") +
ylab("Partial Pearson correlation") + theme_classic() +
scale_x_discrete(position = "bottom") +
facet_wrap(. ~ fct_inorder(component), scales = "free_x", nrow = 1) +
theme(legend.position = "top",
      axis.text.x = element_text(colour = "black"),
      axis.ticks.x = element_blank(),
      legend.title = element_blank(),
      legend.box.background = element_rect(colour = "black",size = 1),
      strip.text.x = element_blank()) #+ ggtitle("C")


# Correlation plot with CIs (method 2)
ggplot(pcor.ci, aes(x = Model, y=estimate, fill = fct_inorder(Model), 
                    shape = fct_inorder(Model))) + 
geom_point() +
geom_errorbar(width=0.2, aes(ymin = conf.low, ymax = conf.high), 
                position= position_dodge(width = 0.5), colour = "grey60") +
geom_point(size = 2, position = position_dodge(width = 0.5)) +
scale_fill_manual(values = c("red","blue","blue")) +
scale_shape_manual(values = c(21,21,24)) + theme_classic() +
geom_hline(yintercept = 0, linetype = "dashed") +
ylab("Partial Pearson correlation") +
scale_x_discrete(position = "bottom") +
facet_grid(. ~ fct_inorder(component) %>% fct_relabel(~nlist), scales = "free") +
theme(axis.title.x = element_blank(), legend.position = "right",
      axis.text.x = element_blank(), axis.ticks.x = element_blank(),
      strip.background.x = element_blank(),
        legend.title = element_blank(),
      legend.box.background = element_rect(colour = "black"))

# Old (no facetting)
ggplot(sig1, aes(x = 0, xend = Coefficient, y = reorder(compound, Coefficient), 
                 yend = (reorder(compound, Coefficient)))) + 
  geom_segment(arrow = arrow(length = unit(0.1, "inches"), type = "closed"),
               arrow.fill = "blue") + 
  theme_bw() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  xlab("Coefficient on first PLSR latent variable") +
  theme(axis.title.y = element_blank())

ggplot(sig2, aes(x = 0, xend = Coefficient, y = reorder(compound, Coefficient), 
                 yend = (reorder(compound, Coefficient)))) + 
  geom_segment(arrow = arrow(length = unit(0.1, "inches"), type = "closed"),
               arrow.fill = "red") + 
  theme_bw() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  xlab("Coefficient on first PLSR latent variable") +
  theme(axis.title.y = element_blank())

# Coefficient plots

library(ggrepel)

# To change legend order, reorder factor levels
corr <- cor(Bioc0[, -1], Bioc0[, 1], method = "spearman")
pltdata1 <- pltdata %>% mutate(compound1 = ifelse(abs(Coefficient) > 0.022, compound, NA), corr)

p1 <- 
  ggplot(pltdata1, aes(x = Coefficient, y = corr, shape = str_wrap(class, 20))) + 
  geom_point() + theme_bw() +
  theme(panel.grid.major = element_blank(), legend.title = element_blank(),
        legend.position = c(0.85, 0.25),
        legend.key.size = unit(0, "lines")) +
  scale_shape_manual(values = c(15, 1, 19, 25, 22, 14, 3, 4)) +
  xlab("Coefficient on first PLSR latent variable (p1)") + 
  ylab("Spearman correlation WCRF score - metabolite") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_text_repel(aes(label = compound1), size = 3) #+
  #ggtitle("A")

corr1 <- cor(Facid[, -1], Facid[, 1], method = "spearman")
faplot1 <- faplot %>% mutate(compound1 = ifelse(abs(Coefficient) > 0.045, compound, NA), corr1)

p2 <- ggplot(faplot1, aes(x = Coefficient, y = corr1, shape = class)) + geom_point() + 
  theme_bw() + xlim(-0.19, 0.19) + ylim(-0.22, 0.22) +
  theme(panel.grid.major = element_blank(), legend.title = element_blank(),
        legend.position = c(0.85, 0.2),
        legend.key.size = unit(0, "lines")) +
  scale_shape_manual(values = c(6, 16, 1, 4, 3)) +
  xlab("Coefficient on 1st PLSR latent variable (p1)") + 
  ylab("Spearman correlation WCRF score - metabolite") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_text_repel(aes(label = compound1), size = 3) #+
  #ggtitle("B")


# Generate aligned plots
library(cowplot)
plot_grid(p1, p2, nrow = 2, labels = c("A", "B"), label_size = 12) %>%
  save_plot("s_plots.pdf")

both <- align_plots(p1, p2, align = "hv", axis = "tblr")
ggdraw(both[[1]])
ggsave("endogenous.png", height = 100, width = 180, units = "mm")
ggdraw(both[[2]])
ggsave("FAs.png", height = 100, width = 180, units = "mm")

# Venn diagram for compounds
library(VennDiagram)
venn.diagram(list(Controls = colnames(ctrlA), CRC1 = colnames(ctrlB), CRC2 = colnames(ctrls)), 
             imagetype = "png", filename = "compound_venn.png", 
             height=150, width=150, units="mm", cat.fontfamily = "", fontfamily = "")

# Biocrates and FAs together in facetted plot (couldn't put classes in right order)
all <- bind_rows(Endogenous = pltdata, `Fatty acids` = faplot, .id = "Metabolites")

ggplot(all, aes(y = Class, x = Coefficient, colour = Class)) + 
  geom_jitter(height = 0.05) + 
  xlab("Coefficient from first PLS latent variable") +
  theme_bw() + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme(legend.position = "none", axis.title.y = element_blank(),
        axis.line.y = element_line()) +
  facet_grid(Metabolites ~ ., scales = "free", space = "free", switch = "y")

# Old coefficient scatter (top and bottom percentiles)

# Vector of black and grey for plot points
vec <- c( rep("black", n.low), rep("grey", nrow(dat) - nrow(dat1)), rep("black", n.high) )

# Now plot data, adding text
plot(sort(coeff$value), pch = 17, col=vec, xlab = "", ylab = "Coefficient",
     main = paste(nrow(mod$scores), "fasted subjects, optimal dimensions =", lv))
# High and low labels
text(nrow(dat) : (nrow(dat) - n_top), df1$Coefficient, df1$compound, pos=2, cex = 0.6)
text(1:nrow(df2), df2$Coefficient, df2$compound, pos=4, cex=0.6)
abline(a=0, b=0, lty = "dotted")
