---
title: "Tables for manuscript"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table 2: Characteristics of study population CRC1

|                            |Cncr_Caco_Clrt: 0 (N = 492) |Cncr_Caco_Clrt: 1 (N = 496) |
|:---------------------------|:---------------------------|:---------------------------|
|**Sex**                     |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; Female         |189 (38)                    |190 (38)                    |
|&nbsp;&nbsp; Male           |303 (62)                    |306 (62)                    |
|**Age at blood collection** |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean           |56.55 &plusmn; 7.96         |56.55 &plusmn; 8.01         |
|**Height**                  |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |163.35 &plusmn; 9.31        |164.17 &plusmn; 9.02        |
|**Weight**                  |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |70.98 &plusmn; 11.76        |73.03 &plusmn; 13.85        |
|**BMI**                     |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |26.58 &plusmn; 3.72         |27.06 &plusmn; 4.51         |
|**Total energy intake**     |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |2,163.31 &plusmn; 622.15    |495;  NA &plusmn;  NA       |
|**Country**                 |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; France         |24 (5)                      |24 (5)                      |
|&nbsp;&nbsp; Italy          |205 (42)                    |206 (42)                    |
|&nbsp;&nbsp; Germany        |114 (23)                    |116 (23)                    |
|&nbsp;&nbsp; Spain          |45 (9)                      |45 (9)                      |
|&nbsp;&nbsp; Netherlands    |40 (8)                      |40 (8)                      |
|&nbsp;&nbsp; UK             |23 (5)                      |24 (5)                      |
|&nbsp;&nbsp; Greece         |41 (8)                      |41 (8)                      |
|**Physical activity**       |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |491;  NA &plusmn;  NA       |91.31 &plusmn; 55.83        |
|**Smoking status**          |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; Never smoker   |260 (53)                    |241 (49)                    |
|&nbsp;&nbsp; Non-smoker     |137 (28)                    |149 (30)                    |
|&nbsp;&nbsp; Smoker         |92 (19)                     |102 (21)                    |
|&nbsp;&nbsp; Unknown        |3 (1)                       |4 (1)                       |
|**WCRF score**              |&nbsp;&nbsp;                |&nbsp;&nbsp;                |
|&nbsp;&nbsp; mean (sd)      |479;  NA &plusmn;  NA       |480;  NA &plusmn;  NA       |


## Table 2: Characteristics of study population CRC1

|                            |Cncr_Caco_Clrt: 0 (N = 1,185) |Cncr_Caco_Clrt: 1 (N = 1,185) |
|:---------------------------|:-----------------------------|:-----------------------------|
|**Sex**                     |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; Female         |577 (49)                      |577 (49)                      |
|&nbsp;&nbsp; Male           |608 (51)                      |608 (51)                      |
|**Age at blood collection** |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean           |57.22 &plusmn; 7.61           |57.33 &plusmn; 7.60           |
|**Height**                  |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |166.30 &plusmn; 9.21          |166.70 &plusmn; 9.38          |
|**Weight**                  |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |73.16 &plusmn; 13.44          |75.57 &plusmn; 14.28          |
|**BMI**                     |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |26.39 &plusmn; 3.97           |27.14 &plusmn; 4.34           |
|**Total energy intake**     |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |2,166.43 &plusmn; 649.86      |1,180;  NA &plusmn;  NA       |
|**Country**                 |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; France         |28 (2)                        |28 (2)                        |
|&nbsp;&nbsp; Italy          |184 (16)                      |184 (16)                      |
|&nbsp;&nbsp; Germany        |203 (17)                      |203 (17)                      |
|&nbsp;&nbsp; Spain          |198 (17)                      |198 (17)                      |
|&nbsp;&nbsp; Netherlands    |99 (8)                        |99 (8)                        |
|&nbsp;&nbsp; UK             |44 (4)                        |44 (4)                        |
|&nbsp;&nbsp; Greece         |122 (10)                      |122 (10)                      |
|**Physical activity**       |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |1,164;  NA &plusmn;  NA       |1,163;  NA &plusmn;  NA       |
|**Smoking status**          |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; Never smoker   |533 (45)                      |480 (41)                      |
|&nbsp;&nbsp; Non-smoker     |359 (30)                      |388 (33)                      |
|&nbsp;&nbsp; Smoker         |279 (24)                      |300 (25)                      |
|&nbsp;&nbsp; Unknown        |14 (1)                        |17 (1)                        |
|**WCRF score**              |&nbsp;&nbsp;                  |&nbsp;&nbsp;                  |
|&nbsp;&nbsp; mean (sd)      |1,140;  NA &plusmn;  NA       |1,127;  NA &plusmn;  NA       |

## Table 2: Characteristics of the study population all EPIC, see CRC_models.R

|                          |fullepic (N = 491,992)    |
|:-------------------------|:-------------------------|
|**Sex**                   |&nbsp;&nbsp;              |
|&nbsp;&nbsp; Female       |148,007 (30)              |
|&nbsp;&nbsp; Male         |343,985 (70)              |
|**Height**                |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |165.99 &plusmn; 8.95      |
|**Weight**                |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |70.25 &plusmn; 13.72      |
|**BMI**                   |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |25.44 &plusmn; 4.30       |
|**Total energy intake**   |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |485,793;  NA &plusmn;  NA |
|**Country**               |&nbsp;&nbsp;              |
|&nbsp;&nbsp; France       |68,757 (14)               |
|&nbsp;&nbsp; Italy        |46,353 (9)                |
|&nbsp;&nbsp; Germany      |40,791 (8)                |
|&nbsp;&nbsp; Spain        |81,678 (17)               |
|&nbsp;&nbsp; Netherlands  |37,394 (8)                |
|&nbsp;&nbsp; UK           |26,916 (5)                |
|&nbsp;&nbsp; Greece       |49,547 (10)               |
|**Physical activity**     |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |423,825;  NA &plusmn;  NA |
|**Smoking status**        |&nbsp;&nbsp;              |
|&nbsp;&nbsp; Never smoker |239,307 (49)              |
|&nbsp;&nbsp; Non-smoker   |130,798 (27)              |
|&nbsp;&nbsp; Smoker       |110,191 (22)              |
|&nbsp;&nbsp; Unknown      |11,696 (2)                |
|**WCRF score**            |&nbsp;&nbsp;              |
|&nbsp;&nbsp; mean (sd)    |397,634;  NA &plusmn;  NA |


## Table 4: Compounds most contributing to metabolic signatures of WCRF score and importance in the PLS model
